# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_big_int', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_charfield', models.CharField(blank=True, max_length=255, null=True)),
                ('a_date', models.DateTimeField(blank=True, null=True)),
                ('other_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anothermodel',
            name='a_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OneModel'),
        ),
    ]
